### ISSUE TITLE
Can it be used as the factory firmware for LilyGo's T-Watch?

### ISSUE THREAD

**Issue by lewisxhe** [sharandac/My-TTGO-Watch#1]
Hi, the UI you made is very good. Can it be used as the factory firmware for LilyGo's T-Watch?

**Comment by sharandac** [comment]
Gladly! But please give me another 3-4 weeks to get the environment ready for a first useable release with some examples.

**Comment by lewisxhe** [comment]
Okay, I'm glad you can share your new project. We will use your firmware when T-Watch leaves the factory. And I have declared to use your firmware in the README in the Library.
