### ISSUE TITLE
Chat group for this project

### ISSUE THREAD

**Issue by ssspeq** [sharandac/My-TTGO-Watch#100]
I was wondering if there is some kind of chatgroup or something along those lines for this project? Telegram, irc, something like that? If not, perhaps one could be created?

**Comment by ua6ahp** [comment]
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library - it is a "Arduino-ready" library. SimpeWatch can be loaded from examples - TTGO TWatch Library -> LVGL -> SimpleWatch.  Read how to configure on the above page.

Before uploading, you may need to uncomment the line
//#define LILYGO_WATCH_2020_V1                  // To use T-Watch2020 , please uncomment this line
in config.h file.

But there will be no additional applications in the firmware. But the interface is more convenient there.

**Comment by datacute** [comment]
Gitter.io allows signing in with github account, and creating groups for your github repositories.

**Comment by ssspeq** [comment]
I took the liberty of creating a telegram group if anyone is interested.

https://t.me/TTGO_Watch
