### ISSUE TITLE
Guru Meditation Error

### ISSUE THREAD

**Issue by rnisthal** [sharandac/My-TTGO-Watch#104]
The web server was working great after updating wdt time.

Today I pulled #101, #102 and #103 and I get into a bootloop with this error:

Guru Meditation Error: Core 0 panic'ed (Cache disabled but cached memory region accessed)

I'd think this is related to #103 

I think a reliable web server helps for user configuration.
In my case I'm programming a way to have a custom background loaded from a file in SPIFFS, and this file could be easily changed through the web server.

Any thoughts?

**Comment by sharandac** [comment]
I am a little surprised. #103 is not relevant for the master branch and has not been merged. Only #101 and #102 could have caused this.
I think that the sound module causes problems and does not work with psram.
I'm a bit unhappy with the webserver and consider using a non asynctcp based webserver in the future.
I will have a look at it right now.
