### ISSUE TITLE
Fix compiler warning

### ISSUE THREAD

**Issue by jcwren** [sharandac/My-TTGO-Watch#118]
Any chance someone could fix the compiler warning `<command-line>:0:10: warning: ISO C99 requires whitespace after the macro name` that occurs on EVERY file? There's also a few other warnings thrown out, but I'm not sure how many are in the project and how many are from the Espressif code or other modules.

**Comment by datacute** [comment]
My workaround is recorded here
https://github.com/sharandac/My-TTGO-Watch/issues/34

Related pull requests:
https://github.com/platformio/platform-espressif32/pull/378
https://github.com/espressif/arduino-esp32/pull/4289
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/issues/15
