### ISSUE TITLE
Timezone resets to utc-0 after sleep

### ISSUE THREAD

**Issue by EverlastEngineering** [sharandac/My-TTGO-Watch#12]
If I connect to wifi with rtc update enabled, the time shows properly. Currently, I'm -4 utc. It shows 10:52. If I sleep and wake the device, it shows 06:52 until I reconnect wifi.

**Comment by sharandac** [comment]
i know. the api for the time settings are not very good. i think i will reimplement that over the days.

**Comment by EverlastEngineering** [comment]
Still happening I'm afraid.

**Comment by EverlastEngineering** [comment]
(If that commit from earlier was an attempt to fix it.)
