### ISSUE TITLE
Touch screen does not work on TWatch 2019 with touch

### ISSUE THREAD

**Issue by ddv2005** [sharandac/My-TTGO-Watch#123]
Hello,

I just bought TTGO T-Watch 2019 with touch but touch screen is unusable because it use different resolution and orientation. TWatch Library handle getPoint from sensor differently for 2020 and 2019 versions but My-TTG_Watch has own touch_getXY code that use touch sensor directly and not compatible with 2019. For 2019 you don't need to mirror it and have to scale from 320x320 to 240x240. 

Also https://github.com/sharandac/My-TTGO-Watch/issues/18 fix in touch_getXY make impossible to use on screen keyboard because no way to click backspace and etc

**Comment by sharandac** [comment]
This project is explicit for the T-Watch 2020 and not for the T-Watch 2019, which would require adjustments.

**Comment by wlcims** [comment]
The touch screens of T-Watch2019 and T-Watch2020 are reversed, you can see here #77
