### ISSUE TITLE
IR remote working? 

### ISSUE THREAD

**Issue by ondragu** [sharandac/My-TTGO-Watch#129]
Hello,
I was trying out IR but didnt see any flashing of the LED through my Smartphone camera. It worked always with my IR-LEDs.
Did anyone had success with IT? 
I would like to insert my own codes. 
Greetings 
Christopher

**Comment by jakub-vesely** [comment]
I can confirm that it works form, at least I can see flashing the IR LED when I press a button in IR Remote app (I've never tested with a Samsung TV)

**Comment by ondragu** [comment]
So it seems my IR LED ist broken. Have the latest firmware flashed.
