### ISSUE TITLE
Question: Is it possible to record audio from the speaker?

### ISSUE THREAD

**Issue by zenflow** [sharandac/My-TTGO-Watch#139]
I know a speaker hardware can typically also be used as a microphone.. Is it possible to configure the pin connected to the speaker to be input to ADC instead of output from DAC?

Then we could do some really cool stuff, including a sound recorder app, & perhaps using [speech-to-text processing](https://github.com/mozilla/DeepSpeech) in the cloud to interpret commands.

**Comment by NorthernDIY** [comment]
Not possible. The max 98357 is an integrated DAC/amplifier that attaches via i2s.  It is output only and does not handle analog signals.

**Comment by zenflow** [comment]
Thanks for the prompt response @NorthernDIY Keep up the great work!
