### ISSUE TITLE
Does not complie when using the current version of TTGO_TWatch_Library

### ISSUE THREAD

**Issue by Pickelhaupt** [sharandac/My-TTGO-Watch#141]
Since the touch screen driver was updated to the focaltech driver, touch.cpp will not compile due to major changes to the classes in the driver. Attaching a modified version of touch.cpp that works with the new driver. It will not work with the old touch driver though. Found a bug, will add code when sorted
Cheers,
Jesper

**Comment by sharandac** [comment]
I think it is better to wait for the 1.4.0 release. Then the API is stable and can be used safely.
