### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by 5tormChild** [sharandac/My-TTGO-Watch#144]
@sharandac did a very great and respectable work, he created a working firmware instead of LilyGO.
But more than 3 weeks had passed and the project seems to be dead ATM.
My C knowledge is limited, I could help with Free Pascal / Delphi / Lazarus stuff, but maybe LilyGO could provide the needed resources to keep this project going.
Still, it's impressive how far did this project go from what LilyGO "provided"!

**Comment by NorthernDIY** [comment]
I don't think the project is dead at all.

What's likely is that autumn has brought with it additional time requirements from work/school/family and the resurgence of the pandemic.

As soon as I am done with my classes for the semester I intend to jump right back into this.

**Comment by 5tormChild** [comment]
Thanks, @NorthernDIY!

**Comment by madjestic** [comment]
3 weeks of no commits and you declare the project dead?  Kids, you are funny.  Get a life or send pull requests.

**Comment by anarchking** [comment]
@madjestic..... GitHub is for DEVELOPMENT of projects and community, A simple Point in the right direction Would have worked. Like telling them that they could look at history or comments.
