### ISSUE TITLE
Gadgetbridge nie wykrywa watch 

### ISSUE THREAD

**Issue by sim1988son** [sharandac/My-TTGO-Watch#146]
Mam telefon xiaomi mi note 10 i watch paruje się z telefonem, ale aplikacja nie odnajduje go. Mam wgrany program experimental. I co dalej?

**Comment by Neuroplant** [comment]
If the phone is already connected to the watch, you have to un-check "ignore connected devices" option in the settings of Gadgetbridge.
If it still not works, a reboot of the phone does wonders.
But I think here is not the place to discuss Gadgetbridge issues.

Neuroplant
