### ISSUE TITLE
new design

### ISSUE THREAD

**Issue by Roy-Ermers** [sharandac/My-TTGO-Watch#147]
Hey everyone.

I've bought this thing with the idea to make a really handy watch. But I've come to discover that my C++ knowledge isn't that great and I don't have the time to invest in learning c++. However, I did have the time to design a few bits for the watch, and I think it would benefit this project. I'm going to drop a figma link, I'm open for criticism or new features. Let me know what you think.

https://www.figma.com/file/v49rIEz8Az18nsSyIjxSJH/Watch?node-id=0%3A1

**Comment by sim1988son** [comment]
Super

**Comment by FantasyFactory** [comment]
interesting
