### ISSUE TITLE
Image flipped upside-down

### ISSUE THREAD

**Issue by slaff** [sharandac/My-TTGO-Watch#162]
I am having a problem with the image on the watch being upside-down. Is there a setting that I need to change in order to have the right orientation? If this is a known feature, please lead me to the URL where I can read more.

P.S: Thanks a lot to all people involved in this project for the great job!

![image](https://user-images.githubusercontent.com/247452/102610860-30ebe880-412e-11eb-8198-dac398290dac.png)

**Comment by sharandac** [comment]
You can find the display orientation in the display menu.

![screen4](https://user-images.githubusercontent.com/47607486/102627496-90ef8880-4148-11eb-88de-5a2232db3f7a.png)

**Comment by slaff** [comment]
> the display menu.

Ok, that sounds very good but how to access the display settings? Is there a documentation/tutorial somewhere?

**Comment by slaff** [comment]
Found it. Had to scroll one screen down and then one screen to the right. Thank you again for your help and work! Awesome stuff!
