### ISSUE TITLE
Add function 

### ISSUE THREAD

**Issue by Rico8414** [sharandac/My-TTGO-Watch#169]
Hello,

A big thank you for this application, I use it with pleasure every day. I imagine the time and skill spent writing the code. Once again thank you. Like I'm bad at programming. I had a function on my old CASIO to beep every hour. Will it be possible to create this function?
Thank you and good day. Sorry if my English is still very imperfect, but I'm making an effort.

See you soon

**Comment by guyou** [comment]
Seems quite related to this attempt: https://github.com/wfdudley/T-watch-2020/blob/master/appStopWatch.cpp
