### ISSUE TITLE
xtensa-esp32-elf-g++: error: src\my-ttgo-watch.ino.cpp: No such file or directory

### ISSUE THREAD

**Issue by madjestic** [sharandac/My-TTGO-Watch#171]
Hello,

I just tried building the project and I am getting the following compilation error:
`
<command-line>:0:10: warning: ISO C++11 requires whitespace after the macro name
Compiling .pio\build\ttgo-t-watch\src\my-ttgo-watch.ino.cpp.o
xtensa-esp32-elf-g++: error: src\my-ttgo-watch.ino.cpp: No such file or directory
xtensa-esp32-elf-g++: fatal error: no input files
compilation terminated.
`

Cheers,
Vlad

**Comment by sharandac** [comment]
Wait a moment and try again. This is a bug in PlatformIO that also happens to me from time to time.

**Comment by madjestic** [comment]
it compiles on Linux ok, odd...
