### ISSUE TITLE
Set static IP for wifi.

### ISSUE THREAD

**Issue by benalb** [sharandac/My-TTGO-Watch#173]
This a special case, but I would like to know if it is possible to set a static IP for wifi. My local net is open but does not have a dhcpcd server, so the watch keep on trying to connect, without success. 
I was thinking on create a wificfg.json in the /data dir, but I don't know the format of the file.

**Comment by sharandac** [comment]
Currently, setting a static IP is not supported. Maybe in the future, if someone wants to implement this.

**Comment by benalb** [comment]
Ok, time to set up a dhcp server. Thank you, I'm closing the issue.
