### ISSUE TITLE
Add support for watchface

### ISSUE THREAD

**Issue by guyou** [sharandac/My-TTGO-Watch#174]
Would be useful to have support for watchfaces, letting user to change the look'n'feel of the main screen.
Watch faces example: https://getwatchmaker.com/collection/Square
Would be great to have similar possibilities.

**Comment by guyou** [comment]
As references:

* One project with faces in mind: https://github.com/AlexGoodyear/agoodWatch
* Another one with multiple faces: https://github.com/wfdudley/T-watch-2020
* A funny face: https://github.com/wizche/ttgo-smb

**Comment by guyou** [comment]
I've just discovered a project with a **HUGE** collection of faces: https://twatchbuilder.com/
But the code seems quite closed...

Perhaps a sort of inspiration for a face framework.

**Comment by sharandac** [comment]
spiffs content
```
watchface_dial.png
watchface_hour.png
watchface_hour_s.png
watchface_min.png
watchface_min_s.png
watchface_sec.png
watchface_sec_s.png
```
watchface_theme.json
```json
{
  "hour": {
    "enable": true,
    "x_offset": 0,
    "y_offset": 0
  },
  "min": {
    "enable": true,
    "x_offset": 0,
    "y_offset": 0
  },
  "sec": {
    "enable": true,
    "x_offset": 0,
    "y_offset": 0
  },
  "hour_shadow": {
    "enable": true,
    "x_offset": 5,
    "y_offset": 5
  },
  "min_shadow": {
    "enable": true,
    "x_offset": 5,
    "y_offset": 5
  },
  "sec_shadow": {
    "enable": true,
    "x_offset": 5,
    "y_offset": 5
  }
}
```

**Comment by guyou** [comment]
Nice work.
I understand that such faces are quite similar.

What's the next step to propose more original faces?
In order to keep the idea of an fully external configuration (with files and not C/C++ extension) I can imagine two options:
- a sort of configuration or domain specific language, where moder can describe the background file to load, the position and size (and font) of text, format strings... in order to display step count, time...
- a fully programmable interface using lua (or something like that)

For the first one, we can found reference around animated SVG: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate

**Comment by sharandac** [comment]
the current version has a little support of it. like label keyword, font size, color and format strings

[look here](https://github.com/sharandac/My-TTGO-Watch/blob/master/images/watchface/startrek/watchface_theme.json)

**Comment by guyou** [comment]
This is really awesome. Many thanks.

**Comment by guyou** [comment]
I'm looking for Watchface editors... 
https://v1ack.github.io/watchfaceEditor/ seems promising

**Comment by guyou** [comment]
Once again a big thank for this evolution. I was able to play around in order to add a K2000 comlink face. Funny!

![screen2](https://user-images.githubusercontent.com/47187/117588201-42a44b80-b122-11eb-8828-2ac90e6f3023.png)

**Comment by sharandac** [comment]
Very nice! I made a [repro](https://github.com/sharandac/My-TTGO-Watchfaces) for the watchfaces. Feel free to add it. The app to install it will be coming soon.

**Comment by guyou** [comment]
I was thinking about such watchface-store. My feeling is that another solution is to promote one repo per watchface. This way, no potential licence issue, as each watchface is in its own repository, with the licence decided by its author.
To retrieve them? Look at a GitHub topic: https://github.com/topics/my-ttgo-watch-face
I'm quite sure we can build a webpage fetching all these repo and building a global watchface repository.

**Comment by guyou** [comment]
Hey, and I created an other one.
![image](https://user-images.githubusercontent.com/47187/117730873-654f6680-b1ed-11eb-9578-144a20c82290.png)

**Comment by sharandac** [comment]
Yes, the idea is good. But then we need a definition of what the repro has to look like so that it is easy to use them. The releases do not really work well. The easiest way would be to always have the following files:

```
watchface.tar.gz
watchface_theme_prev_120px.png
watchface_theme_prev_60px.png
watchface_theme_prev.png
```

So it would be enough to set a link to the repro in the watchface_theme_list.json and there you will find these files to use them in the watchface manager I am writing. I download

[https://github.com/sharandac/My-TTGO-Watchfaces/blob/main/watchface_theme_list.json](https://github.com/sharandac/My-TTGO-Watchfaces/blob/main/watchface_theme_list.json)

directly from the watch, which is now possible with the watch.

**Comment by guyou** [comment]
I really don't like the idea of hosting the archive **IN** the repository. In my humble opinion, it is something similar to a chicken-and-egg problem.

What about improving the watchface_theme_list.json structure, allowing an optional link to archive? For example :
```JSON
[
{ "name": "gameboy",
  "url": "https://raw.githubusercontent.com/guyou/my-ttgo-watch-face-gameboy/main/",
  "download": "https://github.com/guyou/my-ttgo-watch-face-gameboy/releases/latest/download/watchface.tar.gz"
},{...}
]
```

I will work on a script to collect all repos with the given topic and build this list.

**Comment by sharandac** [comment]
Ok, I understand. Sounds logical. I'm just finishing the first version to try it out. After that, we'll rebuild it accordingly.

**Comment by sharandac** [comment]
And almost forgotten! Thank you for your constructive help with this project!

**Comment by guyou** [comment]
> And almost forgotten! Thank you for your constructive help with this project!

Thank you you for maintaining this project and keeping it really active.
