### ISSUE TITLE
screenshot download url

### ISSUE THREAD

**Issue by lgrossard** [sharandac/My-TTGO-Watch#212]
Hello,

In USAGE.md, I can read that the screenshot can be downloaded with the following bash command:
wget x.x.x.x/screen.565

which doesn't work and is not consistent with line 170 of webserver/webserver.cpp:
`<li><a target=\"cont\" href=\"/screen.data\">/screen.data</a> - Retrieve the image in RGB565 format, open it with gimp`

The right command is probably:
wget x.x.x.x/screen.data

This is my first contribution, feel free to tell me if I'm doing it the right way.
Regards

BTW, I made a little Python script to generate and download the screenshots from the t-watch, if this helps:
https://ludovic.grossard.fr/media/twatch_screenshot.py

**Comment by sharandac** [comment]
Thanks a lot!
