### ISSUE TITLE
Merging Alarm Clock's widget factory

### ISSUE THREAD

**Issue by guyou** [sharandac/My-TTGO-Watch#214]
The alarm clock application has its own widget factory and widget styles.
See src/app/alarm_clock/widget_factory.* and src/app/alarm_clock/widget_styles.*

What about trying to merge these into main gui library?

First step: the styles. I imagine two solutions:

1. remove widget_styles and use `mainbar_get_*_style`
2. move widget_styles to `src/gui` and replace all `mainbar_get_*_style` by `ws_get_*_style`

Personnaly, I like the second idea, as I do not see any reason why mainbar module is responsible of all widget styles. At the opposite, I imagine that mainbar module should depend on a dedicated style module. But it is just my opinion.

(Note that I'm ready to implement any of these changes)

**Comment by sharandac** [comment]
I also like the second idea best. That would also be the best way to be able to set styles globally. That would also open up other possibilities, such as day/night mode.
