### ISSUE TITLE
Change alarm clock behavior when no day checked

### ISSUE THREAD

**Issue by guyou** [sharandac/My-TTGO-Watch#215]
As a user, when I enable the alarm clock and do not check any week day, I expect it mean **ANY** day, ie the alarm clock will be trigered all the days.

I think it is the behavior I have on my smartphone.

**Comment by sharandac** [comment]
I would have expected that no tag would be activated. But that's right, on the smartphone it means every day.
But I also think that RTCCTL needs an overhaul, now it's a bit hard to use.
