### ISSUE TITLE
The watch randomly wakes up 

### ISSUE THREAD

**Issue by fjgaston** [sharandac/My-TTGO-Watch#239]
first, thank you for wonderful app
I don't know if it's a normal behaviour but my watch (2020 v2) keeps waking up randomly when I barely shake my wrist.
At first I thought that my sleeves tapped the screen but that's not the case. It makes the battery life way lower than I expected.

**Comment by sharandac** [comment]
It sounds as if double-click or tilt is active in the move settings.
