### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by cranphin** [sharandac/My-TTGO-Watch#24]
Hi!

Got watch today, updated to current version from this git using platformio (factory version did not have update function yet).
Wifi works (I can get weather data).
But updating only says update failed, and no message on the console.

Any thoughts?

**Comment by sharandac** [comment]
update is still unstable (HTTPupdate lib). most of the time it runs into an timeout error. only one thing you can do is: try again and again ... or use platformio for updates

**Comment by cranphin** [comment]
Ok, that's usefull to know, thanks! :)

**Comment by JoanMCD** [comment]
an alternative way ...
#27
