### ISSUE TITLE
32px buttons are too small

### ISSUE THREAD

**Issue by fjgaston** [sharandac/My-TTGO-Watch#240]
Hi,
I don't have bog fingers but from what I have tested, it's really hard to touch the 32px buttons, I tried 64px and they are way more easy to touch.
Sometimes with the 32px exit or setting buttons, I really have to touch the button a few times before I'm able to make the damn thing work.
I guess 60px should be fine as it would be easy to with 4 buttons in a row (240px wide)
(btw my watch is 2020v2)

**Comment by sharandac** [comment]
Unfortunately, I think this is due to the rather inaccurate touchscreen. I will get my V2 in 1-2 weeks and can test it myself then. Until then, a little patience is probably necessary.
