### ISSUE TITLE
Add a dimmed mode

### ISSUE THREAD

**Issue by guyou** [sharandac/My-TTGO-Watch#254]
What about adding a mode where backlight is not enabled and minimal information are displayed? Will it save power?

Look at this: https://youtu.be/o3hSAut4N3E?t=130

**Comment by dervomsee** [comment]
I tried it by commenting out the following line: https://github.com/sharandac/My-TTGO-Watch/blob/b6fa212f4f1f13341a9f5b8ae0601413caa52e45/src/hardware/display.cpp#L130
I could almost no longer recognize anything.

**Comment by guyou** [comment]
Do you think it effectively save a significant power?
I have really no idea the ratio between power consumed by display/backlight and the power consumed by CPU.
