### ISSUE TITLE
Alarm app icon is not centered

### ISSUE THREAD

**Issue by Calebe94** [sharandac/My-TTGO-Watch#267]
## Expected Behavior

The icon must be centered like all other applications.

## Current Behavior

![screen](https://user-images.githubusercontent.com/16101480/119283133-75663d80-bc12-11eb-9d5c-05dee11d4447.png)

## Possible Solution

In function `create_alarm_app_icon()`  there is a call to `lv_obj_align` with `LV_ALIGN_IN_TOP_LEFT` as argument. It should be `LV_ALIGN_CENTER`.

I already fixed it. I can submit a PR if you please.

**Comment by sharandac** [comment]
Thanks for your PR!
