### ISSUE TITLE
Forex rates app loses apikey after reboot

### ISSUE THREAD

**Issue by twister077** [sharandac/My-TTGO-Watch#282]
Hi,

The forex rates app loses it's apikey after a reboot.
Have entered the apikey several time and every time after a reboot it's gone.

Maybe a minor issue.

Thanks a lot for all the work.

**Comment by sharandac** [comment]
The error is hopefully fixed in the new firmware version 2021070201.

**Comment by twister077** [comment]
Works perfectly now.
Thx.
