### ISSUE TITLE
Enable crypto ticker app in default build

### ISSUE THREAD

**Issue by twister077** [sharandac/My-TTGO-Watch#284]
A request.
Is it possible to enable the crypto ticker app in the default build?

Thx

**Comment by sharandac** [comment]
unfortunately, the maintainer is lost and i have no contact with him anymore. as a result, the url no longer works to retrieve the data and the app has become useless.

lg Dirk

**Comment by twister077** [comment]
Oke, good to know.
Maybe if I have some time I'll investigate.
