### ISSUE TITLE
Add new Yahoo Finance app

### ISSUE THREAD

**Issue by twister077** [sharandac/My-TTGO-Watch#286]
Hi,

Could you please take a look at this Yahoo Finance API c++ library ([https://github.com/foxadb/yahoo-finance](https://github.com/foxadb/yahoo-finance)) Would it be possible to integrate this in an app? In the same way as the Forex app. Only current spotprice is initial enough.

Yahoo Finance lists stock information as wel as much cryptocurrency information.

Thx

**Comment by PGNetHun** [comment]
Hi!
There are many other finance APIs, which do not require to do 2 webrequest as the Yahoo Finance API C++ library mentioned before. 

These are free APIs (providing JSON or CSV), but you need to register to get ApiKey:
https://iexcloud.io/docs/api/
https://api.tiingo.com/
https://www.alphavantage.co/documentation/
https://financialmodelingprep.com/developer/docs/

The free API pricing plan offer only 15min delay in last stock price, compared to Yahoo Finance near realtime stock price.
