### ISSUE TITLE
WiFi cannot find any access points while scanning.

### ISSUE THREAD

**Issue by spierepf** [sharandac/My-TTGO-Watch#298]
I just installed this firmware, but when I enable WiFi, the scan starts but never shows any access points...

**Comment by sharandac** [comment]
Thanks for your feedback!

Simple question: Which version of the watch are you using?

Sounds like a hardware problem with the wifi antennas to me. Does the problem change when you get extremely close to the AP?

**Comment by spierepf** [comment]
I think you are right, it is a hardware issue. Even basic ESP32 Arduino sketches don't work...
