### ISSUE TITLE
Compile issues on M1 Mac

### ISSUE THREAD

**Issue by 0xPIT** [sharandac/My-TTGO-Watch#326]
Won't compile on M1 Mac with some strange library error.

Fix: fetch LVGL in lib_deps from GitHub: like so `https://github.com/lvgl/lvgl.git#v7.7.2`

**Comment by sharandac** [comment]
Thanks for your feedback. The issue is not only on the M1 Mac, some things has change in PIO or on Github to fetch some code/libs.
