### ISSUE TITLE
Massiv compilation Errors[FIXED]

### ISSUE THREAD

**Issue by MarinGHG** [sharandac/My-TTGO-Watch#327]
Hi, im trying to install the my-ttgo-watch "os" on my watch but I get many compile errors that seem to be caused by lvgl.
These errors come up in pretty much every class:
-----------
                                                                                                                  ^
src/app/alarm_clock/alarm_clock_main.cpp: In function 'rtcctl_alarm_t* alarm_clock_main_get_data_to_store()':
src/app/alarm_clock/alarm_clock_main.cpp:149:60: error: 'lv_switch_get_state' was not declared in this scope
     data.enabled = lv_switch_get_state(alarm_enabled_switch);
                                                            ^
src/app/alarm_clock/alarm_clock_main.cpp:152:53: error: 'lv_btn_get_state' was not declared in this scope
     data.week_days[0] = (lv_btn_get_state(sunday_btn) == LV_BTN_STATE_CHECKED_RELEASED);
                                                     ^
src/app/alarm_clock/alarm_clock_main.cpp:152:58: error: 'LV_BTN_STATE_CHECKED_RELEASED' was not declared in this scope
     data.week_days[0] = (lv_btn_get_state(sunday_btn) == LV_BTN_STATE_CHECKED_RELEASED);
                                                          ^
src/app/alarm_clock/alarm_clock_main.cpp: In function 'void enter_alarm_clock_setup_event_cb(lv_obj_t*, lv_event_t)':
src/app/alarm_clock/alarm_clock_main.cpp:164:19: error: switch quantity not an integer
     switch( event ) {
                   ^
*** [.pio/build/t-watch2020-v2/src/app/alarm_clock/alarm_clock_setup.cpp.o] Error 1
*** [.pio/build/t-watch2020-v2/src/app/alarm_clock/alarm_clock_main.cpp.o] Error 1
--------------
I've installed lvgl trough the platform IO library section, but it didn't help, it only cause more errors.
"My-TTGO-Watch-master/include", seems to be missing
Thank you in advance.

**Comment by sharandac** [comment]
see #326
