### ISSUE TITLE
Buttons are not reacting.

### ISSUE THREAD

**Issue by MarinGHG** [sharandac/My-TTGO-Watch#329]
I installed the newest Version of the My-TTGO Watch and loaded it up but when I open an app, I can't click return. If I press return to close the app i get a haptic feedback but nothing happens other buttons on the keyboard for example work fine. I'm using a TTGO T-watch v2.

**Comment by sharandac** [comment]
Thanks for your feedback! The return/enter button is intended for multi-line entries and has no meaning for single-line entries. The check mark at the bottom right is intended to end/accept the input.

**Comment by MarinGHG** [comment]
I have both, the TTGO T-watch v1 and v2. But I only get this Error on the v2, both are running on the same version.

**Comment by sharandac** [comment]
Ok, thanks for the information. Can you tell me exactly what you did and in which app it occurs so I can track the error exactly?

**Comment by Crsarmv7l** [comment]
I can provide only one specific instance of a button not working.

In utilities, power off only vibrates and does not power off.

I didn't deem it important enough to file an issue since that was my only instance.

**Comment by MarinGHG** [comment]
For me, all buttons that are there to close an app are not working.

**Comment by MarinGHG** [comment]
![%2Fstorage%2Femulated%2F0%2FMIUI%2FGallery%2Fcloud%2F.cache%2F.share%2F.securityshare_temp_files%2F1641749898982.jpg](https://user-images.githubusercontent.com/76157853/148693796-143f70a3-198c-4e1e-ba83-65f5f6dc30c4.jpg)

**Comment by MarinGHG** [comment]
I can Exit Apps by Just Tuning the watch Off and on
