### ISSUE TITLE
the time is 9 minutes slow on my v1 and I have no idea how to fix it

### ISSUE THREAD

**Issue by leftyjoe** [sharandac/My-TTGO-Watch#330]
Hello, I have had this watch for almost a year now, and have been able to compile and upload without any issues, except that the time has consistently been 9ish minutes slow. I have tried with and without using time > sync when connected, and I have gone through several updates and looked for any settings I may be missing, but to no avail. Any help is greatly appreciated.

**Comment by sharandac** [comment]
Thanks for your feedback. I would be interested in the time zone that is set. Perhaps this is responsible for it?

**Comment by leftyjoe** [comment]
Hello, I am in the Pacific time zone, and I tried several time zones
on multiple continents. I have even compiled and built it on different
computers (macOS and Linux). Thanks for your reply, and other than the
time, it is a great project. I am learning a lot.

Thanks,
Joe
