### ISSUE TITLE
Firmware not working on Lilygo T-Watch 2020 V2

### ISSUE THREAD

**Issue by twister077** [sharandac/My-TTGO-Watch#333]
It seems that the firmware isn't working on my V2.
No problems compiling and Serial output is:
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1108
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4

Screen is staying black.

**Comment by sharandac** [comment]
Thanks for your feedback. This is a serial out when no firmware is written into the watch ....
