### ISSUE TITLE
Show sunrise/sunset times

### ISSUE THREAD

**Issue by pavelmachek** [sharandac/My-TTGO-Watch#343]
Would showing sunset/sunrise times be acceptable feature for the watch? I tweaked stopwatch applet to do that for me; code is at https://gitlab.com/tui/My-TTGO-Watch but it needs more polishing and I'm currently configuring user location in C code.

**Comment by Crsarmv7l** [comment]
BTW you can create your own widget through widget factory. Basically you integrate this:

```
#include "gui/widget.h"
#include "gui/widget_factory.h"
#include "gui/widget_styles.h"

icon_t *sunrisesunset_widget = NULL;

LV_IMG_DECLARE(sunrisesunset_64px);

weather_widget = widget_register( "Sunrise/Sunset", sunrisesunset_64px), Callback here);

lv_label_set_text( weather_widget->label, sunrise resolved string );
lv_label_set_text( weather_widget->ext_label, sunset resolved string );
lv_obj_align( weather_widget->label , weather_widget->icon_cont, LV_ALIGN_IN_BOTTOM_MID, 0, 0 );
lv_obj_align( weather_widget->ext_label , weather_widget->icon_cont, LV_ALIGN_IN_TOP_MID, 0, 0 );
lv_label_set_align( weather_widget->label, LV_LABEL_ALIGN_CENTER );
lv_label_set_align( weather_widget->ext_label, LV_LABEL_ALIGN_CENTER );

```

You probably dont need the alignments, I think they are already outlined in the widget includes. You can get fancy and have it change the widget image (eg a rising sun in the morning and a setting sun at night), by re-purposing sharandac's src_icon code in bluetooth_message.

I am at best a novice but I spent quite a while creating a BLE weather message widget with changing image based on the weather conditions, so maybe this could help you.
