### ISSUE TITLE
Build all environment in CI

### ISSUE THREAD

**Issue by guyou** [sharandac/My-TTGO-Watch#350]
Since the firmware can be used on many environments, it could be useful to have CI to check that all of these are building fine.

I did two experiments around this:

* building all env in one Job (took around 30 min): 
  * result: https://github.com/guyou/My-TTGO-Watch/actions/runs/1921918021
  * code: https://github.com/guyou/My-TTGO-Watch/blob/ci-build-all-env/.github/workflows/main.yml
* using a matrix build (took 7 min and used 10 workers):
  * result: https://github.com/guyou/My-TTGO-Watch/actions/runs/1922979010
  * code: https://github.com/guyou/My-TTGO-Watch/blob/ci-build-all-env-matrix/.github/workflows/main.yml

Let me know what solution have your preference and I will create a pull-request.

**Comment by sharandac** [comment]
Thank you for your suggestion. I have tried the second variant and inserted it into the experimental branch.
