### ISSUE TITLE
serial.serialutil.SerialTimeoutException: Write timeout - Can anyone help?

### ISSUE THREAD

**Issue by ParadoxArudino** [sharandac/My-TTGO-Watch#352]
![image](https://user-images.githubusercontent.com/90871937/156849568-6aa116ce-8842-4c68-ad00-b918f587fe1d.png)

Does anyone know what is causing this? It is the same with multiple different sketches. It is a V3 watch so it is using the "T-Watch Base" in board manager revision. Thanks, Paradox

**Comment by felipeMan** [comment]
I´m using the 2019 version in platformio IDE, and shows this behavior too.
In my case the following steps "work":
1- turn off t-watch
2- upload the firmware from the ide
3 - push power button and hold it until the connection start
I hope this help! regards
