### ISSUE TITLE
Support for twatch2019+SIM868

### ISSUE THREAD

**Issue by felipeMan** [sharandac/My-TTGO-Watch#353]
Hi Guys,
I bought the twatch 2019 version+SIM868 variation. and I clone github/compile/upload the code using platformio IDE.
My HW start and show several msgs via uart, also the images are showed, but have some problems, i.e.

-The touch have a inverted behavior. 
that mean when I drag form right to left, the display image movement is in the inverted direction (left to right). 
In the up down and down up gesture the behavior is inverted too.

I think maybe just rotate the display should align the images position and gesture actions. I will test this in the next week.

My question is if exist any project variant for the 2019 version?
Thanks in advance, regards!

**Comment by sharandac** [comment]
Thanks for your feedback. So far there is no port for the 2019 variant, also because I don't have the hardware to be able to test it accordingly.
