### ISSUE TITLE
Bad check in src/utils/uri_load/uri_load.cpp ...?

### ISSUE THREAD

**Issue by asdf23** [sharandac/My-TTGO-Watch#359]
Greetings,
I noticed an  odd thing. I cannot explain it. In the following lines of code for me httpCode is set to -1. Or perhaps that's just what I'm seeing from a log I set `URI_LOAD_ERROR_LOG("httpCode: %d", httpCode);` anyway I see a -1 but it is still entering this if block. I believe that the line should be  something like `if( httpCode != -1 && ... ) ` or just  `httpCode == HTTP_CODE_OK`

Honestly I don't understand what is going on

```
int httpCode = download_client.GET();
URI_LOAD_ERROR_LOG("httpCode: %d", httpCode);   <-- show's -1
if ( httpCode > 0 && httpCode == HTTP_CODE_OK  ) {
    URI_LOAD_ERROR_LOG(" inside if");  <-- loop is entered !?
```

**Comment by sharandac** [comment]
Thank you for your feedback. You're right, that probably happened during development and got left behind. It will be fixed in the next version.
