### ISSUE TITLE
Infinite loop..?

### ISSUE THREAD

**Issue by asdf23** [sharandac/My-TTGO-Watch#360]
https://github.com/sharandac/My-TTGO-Watch/blob/6b00fe68746ef01406243af5a57c26ba3f1905a3/src/utils/uri_load/uri_load.cpp#L406

I've been adding more debugging and found an infinite loop. Where's what I'm seeing:

![image](https://user-images.githubusercontent.com/4165735/165989449-7e38388d-491f-455b-a7aa-a066b99f2979.png)

**Comment by sharandac** [comment]
Thank you for your feedback. The loop is terminated when the connection times out and no bytes left to receive ( connection AND bytes left > 0 ). The inner condition checks if bytes are left in the stream buffer. This can take a while. See ...

https://github.com/sharandac/My-TTGO-Watch/blob/6b00fe68746ef01406243af5a57c26ba3f1905a3/src/utils/uri_load/uri_load.cpp#L378
