### ISSUE TITLE
Question: Why the switch to NimBLE?

### ISSUE THREAD

**Issue by Crsarmv7l** [sharandac/My-TTGO-Watch#364]
Just curious why you decided to switch to NimBLE?

**Comment by sharandac** [comment]
Good question, simple answer:

- more stable
- much less internal RAM consumption

**Comment by Crsarmv7l** [comment]
Appreciate the response. The RAM part is self explanatory, but when you say more stable how do you mean? Connection wise?

I am weighing incorporating it in my fork, but would have to do it by hand.

**Comment by Crsarmv7l** [comment]
Ah yes I have noticed that occasionally the phone/watch wont connect and need to be re-paired. Thanks for the insight.
