### ISSUE TITLE
T-Watch v3 failed to build

### ISSUE THREAD

**Issue by marsmaennchen** [sharandac/My-TTGO-Watch#365]
I tried to build the T-Watch v3 firmware with PlatformIO on Windows as seen on Youtube  (ShotokuTech).
At the end i get following errors in the Terminal.

`In file included from .pio/libdeps/t-watch2020-v3/ESP Mail Client/src/wcs/esp32/ESP32_SSL_Client.h:40:0,
                 from .pio/libdeps/t-watch2020-v3/ESP Mail Client/src/wcs/esp32/ESP32_SSL_Client.cpp:44:
.pio/libdeps/t-watch2020-v3/ESP Mail Client/src/./wcs/base/TCP_Client_Base.h: In member function 'int TCP_Client_Base::setTimestamp(time_t)':
.pio/libdeps/t-watch2020-v3/ESP Mail Client/src/./wcs/base/TCP_Client_Base.h:166:24: error: variable 'TCP_Client_Base::setTimestamp(time_t)::timeval tm' has initializer but incomplete type
         struct timeval tm = {ts, 0}; // sec, us
                        ^
.pio/libdeps/t-watch2020-v3/ESP Mail Client/src/./wcs/base/TCP_Client_Base.h:167:52: error: 'settimeofday' was not declared in this scope
         return settimeofday((const timeval *)&tm, 0);
                                                    ^
*** [.pio\build\t-watch2020-v3\liba37\ESP Mail Client\wcs\esp32\ESP32_SSL_Client.cpp.o] Error 1
In file included from .pio/libdeps/t-watch2020-v3/ESP Mail Client/src/wcs/esp32/ESP32_SSL_Client.h:40:0,
                 from .pio/libdeps/t-watch2020-v3/ESP Mail Client/src/wcs/esp32/ESP32_WCS.h:57,
                 from .pio/libdeps/t-watch2020-v3/ESP Mail Client/src/wcs/esp32/ESP32_WCS.cpp:54:
.pio/libdeps/t-watch2020-v3/ESP Mail Client/src/./wcs/base/TCP_Client_Base.h: In member function 'int TCP_Client_Base::setTimestamp(time_t)':
.pio/libdeps/t-watch2020-v3/ESP Mail Client/src/./wcs/base/TCP_Client_Base.h:166:24: error: variable 'TCP_Client_Base::setTimestamp(time_t)::timeval tm' has initializer but incomplete type
         struct timeval tm = {ts, 0}; // sec, us
                        ^
.pio/libdeps/t-watch2020-v3/ESP Mail Client/src/./wcs/base/TCP_Client_Base.h:167:52: error: 'settimeofday' was not declared in this scope
         return settimeofday((const timeval *)&tm, 0);
                                                    ^
*** [.pio\build\t-watch2020-v3\liba37\ESP Mail Client\wcs\esp32\ESP32_WCS.cpp.o] Error 1
============================================================================================= [FAILED] Took 2067.27 seconds =============================================================================================

Environment     Status    Duration
--------------  --------  ------------
t-watch2020-v3  FAILED    00:34:27.266
========================================================================================= 1 failed, 0 succeeded in 00:34:27.266 ========================================================================================= 

 *  Der Terminalprozess "C:\Users\Patrick\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 't-watch2020-v3'" wurde mit folgendem Exitcode beendet: 1. `

I think the Poblem is anywhere in the "TCP_Client_Base.h"->

`.pio/libdeps/t-watch2020-v3/ESP Mail Client/src/./wcs/base/TCP_Client_Base.h:166:24: error: variable 'TCP_Client_Base::setTimestamp(time_t)::timeval tm' has initializer but incomplete type`
and
`.pio/libdeps/t-watch2020-v3/ESP Mail Client/src/./wcs/base/TCP_Client_Base.h:167:52: error: 'settimeofday' was not declared in this scope`

Does anyone know what to do now?

**Comment by sharandac** [comment]
Thanks for your feedback. It looks like one version has a bug. I have fixed the ESP mail to another version.
