### ISSUE TITLE
TWatch 2021

### ISSUE THREAD

**Issue by playmiel** [sharandac/My-TTGO-Watch#366]
- framework-arduinoespressif32 @ 2.0.4+sha.c5c5909
 - tool-esptoolpy @ 1.30300.0 (3.3.0)
 - tool-mkfatfs @ 2.0.1
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 2.230.0 (2.30)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3

- [x] TWatch 2021

round app not work in twatch2021 the edges of the screen app are unusable and keyboard it to big

it is possible to reduce the size of each application?

**Comment by sharandac** [comment]
Thank you for your feedback. Unfortunately, most apps are not yet adapted for round displays. I have only managed to get the ESP32 working with PSRAM support. I think in the next few weeks I will have managed to work my way through it.
Some apps already have support via the three buttons.

![twatch2021](https://user-images.githubusercontent.com/47607486/181033774-2c64ab55-5ad5-4aeb-9468-6da3cd3c7c97.png)

Maybe I will get some support.

**Comment by playmiel** [comment]
Ah very well I thought that everything was already adapted to the t-watch2021 in this case I will work on my side to adapt each application, I will make a commit if it works well

**Comment by sharandac** [comment]
```c
void foo_tile_setup( uint32_t foo_tile_num ) {
    .
    .
    mainbar_add_tile_button_cb( foo_tile_num, foo_button_event_cb );
}

static bool foo_button_event_cb( EventBits_t event, void *arg ) {
    switch( event ) {
        case BUTTON_EXIT:           mainbar_jump_back();
                                    break;
        case BUTTON_SETUP:          foo_jump_to_setup();
                                    break;
        case BUTTON_REFRESH:        foo_refresh();
                                    break;
    }
    return( true );
}
```
