### ISSUE TITLE
T-Watch V2 - Doesn't compile on Windows PlatformIO.

### ISSUE THREAD

**Issue by Sarah-C** [sharandac/My-TTGO-Watch#372]
I've drawn PlatformIO's attention to the issue as it appears to be only in the Windows PlatformIO version.
https://github.com/platformio/platformio-vscode-ide/issues/3294

```
xtensa-esp32-elf-g++: error: CreateProcess: No such file or directory
*** [.pio\build\t-watch2020-v1\firmware.elf] Error 1

```
I followed the guidance  to remove unused apps, and after cleaning and rebuilding each time. (The project is now on the root of C to prevent overly long paths)..... 
It fails to create the .ELF file no matter how many apps I comment out, including the attempt below!

I'll raise a PlatformIO ticket, but I'm sure they'll regard it as an "edge case".

If anyone knows how to look at the build commands issued internally that are failing, then please feel free to help!

Alternatively - maybe we should create an Elf file and a batch file/exe combo that uploads it to the watch, just as an image so people without Linux aren't locked out of a lovely project?

```
void setup() {
    /**
     * hardware setup
     */
    hardware_setup();
    /**
     * gui setup
     */
    gui_setup();
    /**
     * apps here
     */
    //osmmap_app_setup();
    //weather_app_setup();
    //compass_app_setup();
    //stopwatch_app_setup();
    //tracker_app_setup();
    alarm_clock_setup();
    //activity_app_setup();
    calendar_app_setup();
    //astro_app_setup();
    //mail_app_setup();
    //gps_status_setup();
    IRController_setup();
    //sailing_setup();
    //osmand_app_setup();
    //fxrates_app_setup();
    //powermeter_app_setup();
    //FindPhone_setup();
    //wifimon_app_setup();
    //calc_app_setup();
    //kodi_remote_app_setup();
    /**
     * post hardware setup
     */
    hardware_post_setup();
}
```

**Comment by sharandac** [comment]
Thank you for the feedback! And yes, unfortunately there is no solution for the problem, as it is very Windows-specific. I have heard from some people that they just use WSL2 with VSCode and PlatformIO and it works.
