### ISSUE TITLE
GPS not working

### ISSUE THREAD

**Issue by westhecool** [sharandac/My-TTGO-Watch#377]
**Build tool used:**

- [x] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**used Hardware:**

- [x] TWatch 2020 or TWatch 2021
- [ ] M5Paper
- [ ] M5Core2
- [ ] WT32-SC01

**Description of problem:**
GPS not working on TWatch 2020 V2. GPS status just says "n/a" for all fields.
**Additional information and things you've tried:**
Toggling the GPS on and off

**Comment by sharandac** [comment]
Thank you for your feedback! I can detect software errors. It should be noted that GPS does not work indoors and the GPS receiver of the watch is not very good either.
