### ISSUE TITLE
Any instructions for Arduino IDE?

### ISSUE THREAD

**Issue by iweave1** [sharandac/My-TTGO-Watch#383]
Hi. 
I do not like VS Code, i do not like it's workflow.
But I love this watch. Is there some instructions so that I can use this with Arduino IDE?

**Comment by saubhaagyapurna** [comment]
If it would take too much effort to convert to Arduino IDE, could a makefile be created so that it could be compiled on linux using cross compilation?

**Comment by saubhaagyapurna** [comment]
Found the answer. https://runningdeveloper.com/blog/platformio-project-to-arduino-ide
