### ISSUE TITLE
Config files in a text format e.g JSON

### ISSUE THREAD

**Issue by jbman** [sharandac/My-TTGO-Watch#39]
I tried out downloading and editing the weather config file. Then I discovered that the plain struct is written to the file, so it isn't possible to edit it in a text editor.
Any kind of serialization format which allows to read and modify config data would help with clock set-up. 
Maybe ArduinoJSON could be used?

**Comment by sharandac** [comment]
Done! Please update to 2020081103.

**Comment by jbman** [comment]
Great! Now every setting can be edited by opening http://watch/edit and browsing to the file.
