### ISSUE TITLE
compile error:platformio

### ISSUE THREAD

**Issue by quzx** [sharandac/My-TTGO-Watch#391]
I git cloned this project. With vsc and platformio, i modified platformio.ini like this:
default_envs = t-watch2020-v3
During compile, I got errors like this:
.pio/libdeps/t-watch2020-v3/IRremoteESP8266/src/IRac.cpp:1131:44: error: 'round' is not a member of 'std'
     ac->setSensorTemp(static_cast<uint8_t>(std::round(sensorTemp)));
Then I added condition like this in platformio.ini:
    
[env:t-watch2020-v3]
......
build_flags = 
	-DCORE_DEBUG_LEVEL=3
    -D LILYGO_WATCH_2020_V3
    -D SERIAL_RX_BUFFER_SIZE=256
	-mfix-esp32-psram-cache-issue
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -Os
    -std=c++11
build_unflags = -std=c++98
Then execute pio init --ide==vscode
Build again.
The error is still there.
Can anyone help me? Thanks

**Comment by XanCraft21** [comment]
I had this same problem. Until a fix happens i just made my own round function based off a YouTube tutorial. Do you want me to send a link to the video i found?

Also just in case i would shorten the name of the environment from t-watch-2020-v3 to tw20v3 and do the same for the default environment to prevent the missing file create process error.

**Comment by XanCraft21** [comment]
I believe this question is more for quzx, but since i had the same problem i would like to put my side if that’s ok.

I just used whatever came with the packages i downloaded, that includes the watch package and the C++ and pio packages for vscode. I am not sure which one of those is missing the function.

Which version are you using? I am using the latest version.

I got a popup that asked if i wanted to add a recommended extension, have you done that on your end?

i will send my log once i get some time to do it. Thank you.

**Comment by taidixiong233** [comment]
I had this same problem too.
![image](https://github.com/sharandac/My-TTGO-Watch/assets/60949674/56341e41-6c71-4f17-ae70-8742c06b6070)
![image](https://github.com/sharandac/My-TTGO-Watch/assets/60949674/61d99f0a-001f-401e-b107-ca580a289f82)

**Comment by GDV0** [comment]
Hi taidixiong233,
Could you share the beginning of the log where all software versions are mentionned ?

**Comment by 525bigword** [comment]
I also encountered the same problem, and I also used the environment and bracelet from t-watch version 2020-v3
Vscode version: 1.78.2
PlatformIO IDE version: 3.1.1
Here is my terminal  #log:
![image](https://github.com/sharandac/My-TTGO-Watch/assets/50405154/6736de8c-caea-4865-940b-7c94b523ca16)

**Comment by GDV0** [comment]
Hello 525bigword

It seems I don't have the same IRRemoteESP library installed on my side.
Yours is v2.8.5, while mine is v2.8.4.
I checked the source files of this library and I confirm there is no call to round() function in v2.8.4 but a lot in v2.8.5

**Comment by 525bigword** [comment]
> 你好525大字
> 
> 似乎我没有在我这边安装相同的IRRemoteESP库。你的是 v2.8.5，而我的是 v2.8.4。我检查了这个库的源文件，我确认在 v2.8.4 中没有调用 round（） 函数，但在 v2.8.5 中调用了很多

Thank you, I am a novice. How can I modify the version of the library? I found IRremoteESP8266 in the platformio.ini file, but its version is 2.7.10, as shown in the figure
![image](https://github.com/sharandac/My-TTGO-Watch/assets/50405154/4fd9baa8-b0b4-4bf2-aed4-7b0ef35fa0f5)

**Comment by 525bigword** [comment]
Hello GDV0
After upgrading the IRRemoteESP version to 2.8.4, the same issue still exists
![image](https://github.com/sharandac/My-TTGO-Watch/assets/50405154/adaf2725-0c4a-464b-8eb1-546ad8c12ad8)

**Comment by GDV0** [comment]
525bigword

In the plateformio.ini file the line IRremoteESP8266@> 2.7.10 forces the use of a version of this library > v2.7.10 and automatically loads the latest version if none is already installed.
The latest version of this library is 2.8.5 since May 8, 2023. That's probably why you have such issue.
You can test to replace the line in plateformio.ini file by IRremoteESP8266@ 2.8.4 to force the use of the correct version.

Take care: same problem could occur with other libraries

**Comment by 525bigword** [comment]
> 525bigword
> 
> In the plateformio.ini file the line IRremoteESP8266@> 2.7.10 forces the use of a version of this library > v2.7.10 and automatically loads the latest version if none is already installed. The latest version of this library is 2.8.5 since May 8, 2023. That's probably why you have such issue. You can test to replace the line in plateformio.ini file by IRremoteESP8266@ 2.8.4 to force the use of the correct version.
> 
> Take care: same problem could occur with other libraries

Okay, this issue has been resolved. It's due to the version, and it's mandatory to specify 2.8.4 IRremoteESP8266@2.8.4

**Comment by XanCraft21** [comment]
Even if this did fix the bug the entire code is not usable, it bricks very easily like after a few seconds to a minute of use. I had to use one of the recommended forks, the last one being the best one so far. Thank you for your help.

**Comment by 525bigword** [comment]
> Even if this did fix the bug the entire code is not usable, it bricks very easily like after a few seconds to a minute of use. I had to use one of the recommended forks, the last one being the best one so far. Thank you for your help.

What is the specific issue? For example, automatic restart? Or crash?

**Comment by XanCraft21** [comment]
Repeated crashes during boot. Sometimes it comes up then crashes immediately after a few seconds right back to the boot loop. I made an issue about it.

**Comment by matthewbullweb** [comment]
I had the exact round issue on 2nd try. Did get it to compile once but t watch screen never came on. Just single vibration.

**Comment by devnoname120** [comment]
Did you guys try my fix?
https://github.com/crankyoldgit/IRremoteESP8266/pull/1989

**Comment by matthewbullweb** [comment]
Windows gave me a hard time. A raspberry pi was able to compile firmware without issue in VSCode Platform IO.

**Comment by GDV0** [comment]
I confirm this fix allows to use the  actual IRremoteESP8266 library (v2.8.5)

**Comment by devnoname120** [comment]
@GDV0 Could you open a pull request? As you are the author of #395.

**Comment by devnoname120** [comment]
@GDV0 v2.8.6 is released and contains the https://github.com/crankyoldgit/IRremoteESP8266/pull/1989 fix. See https://github.com/crankyoldgit/IRremoteESP8266/releases/tag/v2.8.6
