### ISSUE TITLE
Hopefully T-Display-S3 TOUCH can be supported.

### ISSUE THREAD

**Issue by urobot2011** [sharandac/My-TTGO-Watch#402]
**used Hardware:**

- [ ] TWatch 2020 or TWatch 2021
- [ ] M5Paper
- [ ] M5Core2
- [ ] WT32-SC01
- [x] T-Display-S3 TOUCH

**Describe the solution you'd like**
I hope T-Display-S3 TOUCH is supported. It has lvgl example, screen size is 170*320.

**Additional context**
[https://github.com/Xinyuan-LilyGO/T-Display-S3/](https://github.com/Xinyuan-LilyGO/T-Display-S3/)

![](https://github.com/Xinyuan-LilyGO/T-Display-S3/raw/main/image/T-DISPLAY-S3-TOUCH.png)

**Comment by sharandac** [comment]
Thanks for your feature request. I think that should be possible without problems. But due to the lack of suitable hardware, this is not possible for me.

**Comment by urobot2011** [comment]
I think I'll be able to make a pull request soon :) 
I'm currently setting up a TFT LCD driver.
