### ISSUE TITLE
TWatch s3 support 

Great job !
I really hope you can make support for the t-watch s3




### ISSUE THREAD

**Issue by Schjonning** [sharandac/My-TTGO-Watch#404]
**used Hardware:**

- [x ] TWatch s3
- [ ] M5Paper
- [ ] M5Core2
- [ ] WT32-SC01

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by crt0mega** [comment]
Sorry to nag/necrobump, but what would be necessary to support the [T-Watch S3](https://www.lilygo.cc/products/t-watch-s3)?
