### ISSUE TITLE
Bluetooth keyboard support?

### ISSUE THREAD

**Issue by datacute** [sharandac/My-TTGO-Watch#46]
Would it be possible to pair with a keyboard? It'd make entering weather API keys so much easier.
Trying to find examples of this are masked by the number of people using esp32 as a bluetooth keyboard!
I did manage to find this code though that looks like a useful example: https://github.com/chegewara/esp32-hid-keyboard-client

**Comment by cranphin** [comment]
Small suggestion, now that json files are used, an easier way to enter the API key is just uploading the right file with your key and lat/lon. E.g. weather.json:
```
{
  "apikey": "YOUR KEY",
  "lat": "YOUR LAT",
  "lon": "YOUR LON",
  "autosync": true,
  "showWind": false
}
```
 You can upload it using the webserver, with the advantage of leaving other configuration/files intact.
Or you can use platformio to 'Upload file system image' in VSCode. You first add the file (and any other configuration files, I include wifi ssid/pw, tz info and display info too for example) to the data folder in the VS project.
This will wipe/overwrite the whole SPIFFS partition, so any existing configuration will be gone.

The easiest way to get samples of the files is just to take them off the watch using the webserver.
