### ISSUE TITLE
Bluetooth problem

### ISSUE THREAD

**Issue by d3th3n** [sharandac/My-TTGO-Watch#49]
There is no way to connect my watch to my iPhone SE 1st generation (just for testing connexion) is "normal" ?

**Comment by sharandac** [comment]
Oh, too bad. Does the Iphone SE1 support BLE? I don't have an iPhone available to test it

**Comment by d3th3n** [comment]
Yes it do ;) my hearing aids work with it... but I can't view my watch inside the Bluetooth device list... I can only view my watch with some ble scan app ! Probably because there no service available for my phone (like message/mail/ ring...)

**Comment by sharandac** [comment]
i use gadgetbridge to send messages to the watch. no idea how it works with iOS and if there is something similar there. but in the end it is just a bluetooth-uart connection and the data is sent as json.

**Comment by d3th3n** [comment]
just one question ... is anyone successful in getting bluetooth to work with an iphone?
