### ISSUE TITLE
Starter questions.

### ISSUE THREAD

**Issue by robouden** [sharandac/My-TTGO-Watch#51]
Thanks all for the nice work on the TTGO Watch2020 software.
I have some simple questions as a starter:

- How to change the background of the watch?
- Are there different themes available?

**Comment by sharandac** [comment]
>     * How to change the background of the watch?
take a look at /src/gui/gui.cpp, line 48 and 60. https://lvgl.io/tools/imageconverter is your friend
>     * Are there different themes available?
no, i have no themes implemented

**Comment by robouden** [comment]
Thanks for the reply. I will have a look.

regards,
rob

**Comment by ondragu** [comment]
I am also looking forward to be able to change the background.
Black looks very good ;-) and perhaps it would reduce energy consumption.

![screen](https://user-images.githubusercontent.com/7092983/90640644-853e9480-e230-11ea-80e2-a34e1c43eb1e.jpg)

**Comment by robouden** [comment]
ondragu,

Did you already make the background like that, or you created the screenshot by other software?

regards
rob

**Comment by sharandac** [comment]
you can take a screenshot with the built in webserver. gimp can read the file as raw, color format is 565. with an resolution of 240x240 pixel.

**Comment by ondragu** [comment]
So did I.
It is a little bit tricky to open it with Gimp, had to rename it to .data.
Then choose the right format (was RGB Big Endian) and you have to say that it is 240x240 pixel.

**Comment by sharandac** [comment]
a good hint to rename the file extension :)

**Comment by datacute** [comment]
On windows, I can view the screenshots in irfanview. If the file extension is .raw then irfanview will ask what format to expect, and it remembers the settings for the next time.

**Comment by FantasyFactory** [comment]
> I am also looking forward to be able to change the background.
/gui/gui.cpp
line 48 `LV_IMG_DECLARE(bg3)`
line 60 `    lv_img_set_src(img_bin, &bg3 );`
you can try the others defaul background simply changing bg3 in bg2, bg1 or bg

> Black looks very good ;-) and perhaps it would reduce energy consumption.
This is not OLED, so black pixel are no power saving

**Comment by robouden** [comment]
I did some more testing and got finally my background the way I wanted. See  screenshot. 
![screenshot_grey](https://user-images.githubusercontent.com/1387190/91721509-db69eb00-ebd3-11ea-890d-71d8d01bec1f.jpg)

BTW.  Enoying the interaction in this channel.

**Comment by sharandac** [comment]
It is not a pro app, but I like hedgehogs :-)

In the future I wanted to build my own framework out of it which is not only suitable for the T-Watch-2020.

**Comment by robouden** [comment]
Got the display even more to my liking with my company name in it. And the bootscreen just the background. 
(Sorry, Dirk I took out the Hedgedog, although I liked the design)

![S1530006](https://user-images.githubusercontent.com/1387190/92111739-b53c8900-ee27-11ea-88f1-681c388b50cc.jpg)
![S1530005](https://user-images.githubusercontent.com/1387190/92111746-b7064c80-ee27-11ea-96e0-f3c256ad8281.jpg)
