### ISSUE TITLE
New App Icon does not appear

### ISSUE THREAD

**Issue by alexkoppelman** [sharandac/My-TTGO-Watch#57]
I am looking to add a new app. Copied the sample app files, renamed all the references and started a draft. 
When I upload however the new app does not appear. 

Does the new app need to be registered somewhere?

**Comment by sharandac** [comment]
Did you also add your app to the my-ttgo-watch.ino? there you have to add the setup function, line 82. do not forget the #include file.

**Comment by alexkoppelman** [comment]
Great! that solved it. For some strange reason I had not visited the .ino file yet.
