### ISSUE TITLE
timezone setting resets to zero on reboot

### ISSUE THREAD

**Issue by joshvito** [sharandac/My-TTGO-Watch#60]
The first two toggles on the time setting screen persist after a reboot, but the timezone must be reset each time I reboot.
I am using a timezone setting of `-5`.

Is this expected or a bug.

**Comment by chrismcna** [comment]
i use +1 timezone and doesn't get reset on restart. Let me try -5 and see what happens

**Comment by chrismcna** [comment]
i can confirm this issue when i set to -5

**Comment by chrismcna** [comment]
i have found the issue, and coded a fix. I will make a pull request for Dirk

**Comment by sharandac** [comment]
Thanks!
