### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by gosymbian** [sharandac/My-TTGO-Watch#71]
Hi,

I have loaded the project into PlatformIO and when I try to build it, I get the following :

> Executing task: C:\Users\Dominique HUGO\.platformio\penv\Scripts\platformio.exe run <

Processing ttgo-t-watch (platform: espressif32; board: ttgo-t-watch; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C:\\DISK_C\\_OneDrive\\Arduino\\Lilygo\\My-TTGO-Watch-master\\.pio\\build\\ttgo-t-watch':
  File "C:\users\dominique hugo\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 155:
    makedirs(env.subst("$BUILD_DIR"))
  File "c:\users\dominique hugo\.platformio\penv\lib\os.py", line 157:
    mkdir(name, mode)
============================================= [FAILED] Took 181.81 seconds =============================================
The terminal process "C:\Users\Dominique HUGO\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.
Terminal will be reused by tasks, press any key to close it.

----------------------------------------------------------------------------------------------------------------------------------------------
and if I try to "upload", I get :

Building in release mode
Compiling .pio\build\ttgo-t-watch\libc15\TTGO TWatch Library\Adafruit_GFX.cpp.o
Compiling .pio\build\ttgo-t-watch\libc15\TTGO TWatch Library\BBQ10Keyboard.cpp.o
Compiling .pio\build\ttgo-t-watch\libc15\TTGO TWatch Library\MPR121.cpp.o
Compiling .pio\build\ttgo-t-watch\libc15\TTGO TWatch Library\TFT_eSPI\Fonts\Font16.c.o
<command-line>:0:10: warning: ISO C99 requires whitespace after the macro name
<command-line>:0:10: warning: ISO C++11 requires whitespace after the macro name
<command-line>:0:10: warning: ISO C++11 requires whitespace after the macro name
<command-line>:0:10: warning: ISO C++11 requires whitespace after the macro name
Compiling .pio\build\ttgo-t-watch\libc15\TTGO TWatch Library\TFT_eSPI\Fonts\Font32rle.c.o
<command-line>:0:10: warning: ISO C99 requires whitespace after the macro name
Compiling .pio\build\ttgo-t-watch\libc15\TTGO TWatch Library\TFT_eSPI\Fonts\Font64rle.c.o
<command-line>:0:10: warning: ISO C99 requires whitespace after the macro name
In file included from .pio\libdeps\ttgo-t-watch\TTGO TWatch Library\src\BBQ10Keyboard.cpp:5:0:
.pio\libdeps\ttgo-t-watch\TTGO TWatch Library\src\BBQ10Keyboard.h:3:18: fatal error: Wire.h: No such file or directory

**************************************************************
* Looking for Wire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Wire.h"
* Web  > https://platformio.org/lib/search?query=header:Wire.h
*
**************************************************************

compilation terminated.
In file included from .pio\libdeps\ttgo-t-watch\TTGO TWatch Library\src\MPR121.cpp:29:0:
.pio\libdeps\ttgo-t-watch\TTGO TWatch Library\src\MPR121.h:5:18: fatal error: Wire.h: No such file or directory

**************************************************************
* Looking for Wire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Wire.h"
* Web  > https://platformio.org/lib/search?query=header:Wire.h
*
**************************************************************

compilation terminated.
*** [.pio\build\ttgo-t-watch\libc15\TTGO TWatch Library\BBQ10Keyboard.cpp.o] Error 1
*** [.pio\build\ttgo-t-watch\libc15\TTGO TWatch Library\MPR121.cpp.o] Error 1
============================================== [FAILED] Took 22.19 seconds ==============================================
The terminal process "C:\Users\Dominique HUGO\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

I have change nothing in code, same .ini downloaded from github
can you advice please ?
thanks in advance,
sincerly,
Domi.

**Comment by chrismcna** [comment]
Hmm, very strange, 
the header is located here for me "C:\Users\Chris\.platformio\packages\framework-arduinoespressif32\libraries\Wire\src"

can you check to see if you have the header under the a similar location

**Comment by chrismcna** [comment]
C:\Users\Chris\.platformio\packages\framework-arduinoespressif32\.piopm 
says im on "version": "3.10004.200129"

**Comment by robouden** [comment]
The error shows wire.h missing seems strange to me. Did you install the espressif32 platform?

regards,
rob

**Comment by gosymbian** [comment]
> The error shows wire.h missing seems strange to me. Did you install the espressif32 platform?
> 
> regards,
> rob

Hi rob,
yeps, espressif32 is installed.

![image](https://user-images.githubusercontent.com/4375274/91026699-66a71780-e5fb-11ea-8ea0-daf7d15c1a73.png)

thanks,
Domi.

**Comment by gosymbian** [comment]
> Hmm, very strange,
> the header is located here for me "C:\Users\Chris\.platformio\packages\framework-arduinoespressif32\libraries\Wire\src"
> 
> can you check to see if you have the header under a similar location

Hi Chris,

yes, I have the files :

![image](https://user-images.githubusercontent.com/4375274/91026932-bab1fc00-e5fb-11ea-892a-5300f7f8ecb7.png)


thanks,
Domi.

**Comment by gosymbian** [comment]
> C:\Users\Chris.platformio\packages\framework-arduinoespressif32\.piopm
> says im on "version": "3.10004.200129"

Hi Chris,

I haven't this file ...

![image](https://user-images.githubusercontent.com/4375274/91027143-fa78e380-e5fb-11ea-8a86-ce68cd910c97.png)

sincerly,
Domi.

**Comment by gosymbian** [comment]
I have re-started from scratch, delete all the directories, ... and everything works fine now ! I can compile and upload the project.

Thanks to all of you for your time & help,
sincerly,
Domi.
