### ISSUE TITLE
Screen is reversed

### ISSUE THREAD

**Issue by gosymbian** [sharandac/My-TTGO-Watch#72]
Hi,

it seems that my screen is rotated by 180 deg ! :-(

![image](https://user-images.githubusercontent.com/4375274/91048048-5737c680-e61b-11ea-98c7-1958fdab5aa2.png)

any idea ?
Thanks, 
Domi.

**Comment by vanvuongngo** [comment]
It's not a bug, it's a feature. When you wear the watch, you can easily use your thumb.
There is a display setting, if you want to change the rotation.

**Comment by gosymbian** [comment]
Wooaa, tkx !! I haven't seen the settings - sorry.

kind regards,
Domi.
