### ISSUE TITLE
Time zone has no effect

### ISSUE THREAD

**Issue by gosymbian** [sharandac/My-TTGO-Watch#73]
Hi,

Time zone has no effect for me, I have tried +2, +3, it always stays on the same hour ...

any clue ?
thanks,
Domi.

**Comment by sharandac** [comment]
After timesync over wifi it show the right time.

**Comment by gosymbian** [comment]
my router doesn't send the time ....

Domi.

**Comment by vanvuongngo** [comment]
Hi Domi,
when I change the time zone it has not immediately  an effect. A timesync after a value change would be pretty. I have to switch off and on again to invoke a timesync.

**Comment by sharandac** [comment]
Please enable timesync like here

![screen](https://user-images.githubusercontent.com/47607486/91056323-201ae280-e626-11ea-8903-04418e6903d2.png)

after next wifi connect the time will sync automaticly.

**Comment by robouden** [comment]
Silly question. But where is the nice grey background image stored in the code? I like to set up the main background like that. (maybe a bit darker).
