### ISSUE TITLE
Crypto ticker & note question

### ISSUE THREAD

**Issue by jcwren** [sharandac/My-TTGO-Watch#75]
Playing around with the various built-in stuff in the latest release. Nice bit of work you've done here!

I've entered BTC for the crypto ticker symbol, but never get an update. Anything I'm missing here?

The Note function doesn't seem to do anything. I haven't dived into the code yet, so maybe that's just a dummy page.

Got the weather update working, had to retype the API key a couple times. That wasn't any fun.

**Comment by robouden** [comment]
It  maybe would have been easier for you maybe to use the webserver and eneter the API key there I think. See attached screenshot on the edit page .
![Screenshot from 2020-08-27 11-10-53](https://user-images.githubusercontent.com/1387190/91376203-82a6f500-e857-11ea-941b-7109993623c7.png)

**Comment by jcwren** [comment]
Ah, cool. I knew it had the web server built in, but I haven't tried that
yet. I for sure didn't know you could edit with it. I was only aware of the
/shot path for screenshots. Might be good to mention some of this early in
the README.md file.

--jc

Save a life; adopt a shelter animal.

**Comment by jcwren** [comment]
If your SSID is too long, the IP address is being clipped. In my case, it's "Keyhole 12 Spy Satellite", and the IP address is 172.16.3.1xx, but the 'xx' is clipped. I know what it is from watching my DHCP server logs, but that's not an easy option for everyone.

**Comment by sharandac** [comment]
Please update to the last version: 2020082701

**Comment by robouden** [comment]
Updated. Runs fine here.
![Screenshot from 2020-08-27 20-20-30](https://user-images.githubusercontent.com/1387190/91436369-eefb1600-e8a2-11ea-8811-f9babea6e908.png)

**Comment by robouden** [comment]
At taking a screenshot it crashed once. After that no issues. Maybe cache issue?
Screen looks nice now. Still I would like to find a way to make a sold grey background.

![screen (5)](https://user-images.githubusercontent.com/1387190/91437772-5fa33200-e8a5-11ea-99a2-ee3c09e21048.jpg)

**Comment by jcwren** [comment]
Still have a problem with the crypto ticker not working on the latest version. I get this error:
```
[I][crypto_ticker_main.cpp:212] crypto_ticker_main_sync_Task(): start crypto ticker main task, heap: 27064
[I][statusbar.cpp:220] statusbar_wifictl_event_cb(): statusbar wifictl event 0002, msg: 172.16.3.131
[I][webserver.cpp:374] asyncwebserver_start(): enable webserver and ssdp
[I][weather.cpp:214] weather_widget_sync_Task(): finish weather widget task, heap: 16904
[E][crypto_ticker_fetch.cpp:100] crypto_ticker_fetch_statistics(): crypto_ticker deserializeJson() failed: InvalidInput
[I][crypto_ticker_main.cpp:244] crypto_ticker_main_sync_Task(): finish crypto ticker main task, heap: 23548
```

**Comment by Thijxx** [comment]
Please re-open. Crypto ticker does not work because no service at URL.

**Comment by sharandac** [comment]
@chrismcna Any information about this issue?

**Comment by Thijxx** [comment]
`#define MY_TTGO_WATCH_HOST    "my-ttgo-watch.co.uk"` in `crypto_ticker_fetch.h` seems to be an invalid source of the ticker data, maybe if you guide me I can test with a working market API from Binance or something

**Comment by sharandac** [comment]
@Thijxx this domain and app is from @chrismcna . i don't know if he's reading this to fix it.
