### ISSUE TITLE
Which version of TWatch are you using?

### ISSUE THREAD

**Issue by lewisxhe** [sharandac/My-TTGO-Watch#76]
Hi, I tried to update and compile the latest firmware, and found that the alignment of characters in the menu has changed. I don’t know which version of TWatch lib you are using. Can you provide a commit id? I have updated lvgl to version 7.3.1 in the TWatch lib, but I think it has nothing to do with this, because the alignment of the original example is correct!

**Comment by lewisxhe** [comment]
![2](https://user-images.githubusercontent.com/22990954/91382671-d2d48600-e85c-11ea-9cf4-e77f766d4d4f.jpg)
![1](https://user-images.githubusercontent.com/22990954/91382677-d49e4980-e85c-11ea-8c3b-113b5975775b.jpg)

**Comment by lewisxhe** [comment]
Because Twatch lib needs to be compatible with multiple boards, I can only try to ensure compatibility with this project. Thank you for the example you wrote for twatch, it is great

**Comment by sharandac** [comment]
Hey, i use the last release 1.2.0. it looks like the definitions are 

`LV_HOR_RES_MAX`

and

`LV_VER_RES_MAX`

are wrong

**Comment by sharandac** [comment]
And I saw that they are planning a new watch 2020 v2. While you are at it, a 32kHz crystal would be great. see here: 

[https://github.com/espressif/esp-idf/issues/947](https://github.com/espressif/esp-idf/issues/947)

This would make it possible to use BLE for a longer period of time while the watch is asleep and save energy.

**Comment by lewisxhe** [comment]
Well, I will suggest adding a 32KHZ crystal! As for the resolution, that is the ST7796 screen size I set it to fit, so you should use lv_disp_get_hor_res() and lv_disp_get_ver_res()

**Comment by sharandac** [comment]
Thanks for the hint! i will adapt. Can you test it?

**Comment by lewisxhe** [comment]
![1](https://user-images.githubusercontent.com/22990954/91413731-1f7c8900-e87e-11ea-9464-817459442a75.jpg)

Ok, I can submit a request to you if needed

**Comment by sharandac** [comment]
looks good. not necessary. i have already changed the corresponding lines in the code.

**Comment by sharandac** [comment]
And another small hardware bug. the covers on the back breaks after a while. all at the same place, near the cutout of the speaker. i think they should be made a bit stronger.

![IMG_20200827_100516](https://user-images.githubusercontent.com/47607486/91414748-48385a80-e84d-11ea-804c-c3f2d143c06b.jpg)

**Comment by lewisxhe** [comment]
Okay, I have given feedback!

**Comment by sharandac** [comment]
I have problems with the new version of TWatch lib. By default DMA is enabled. I have moved the screen memory to the psram to have more internal ram. This causes the dma transfer to crash.

**Comment by lewisxhe** [comment]
I will provide a concise way for LVGL instead of using TFT_eSPI as a driver, because for using LVGL, using TFT_eSPI will undoubtedly consume more ROM, please wait for a while, I will update

**Comment by lewisxhe** [comment]
Please provide your email, we will give you a free watch after testing the 2020V2 version.

**Comment by sharandac** [comment]
A simple way is when use

`#define TWATCH_USE_PSRAM_ALLOC_LVGL`

to disable 

`#define ENABLE_LVGL_FLUSH_DMA`

**Comment by sharandac** [comment]
> Please provide your email, we will give you a free watch after testing the 2020V2 version.

THX! dirk.brosswick@googlemail.com

**Comment by lewisxhe** [comment]
Ok ! If using DMA causes instability, please disable DMA first

**Comment by sharandac** [comment]
This is not possible. Line 104 in TTGO.h force this by default.

**Comment by robouden** [comment]
Lewsx He,

If you need another tester for T-Watch200V2 let me know. I like to test too!!

regards,
Rob Oudendijk

**Comment by lewisxhe** [comment]
I will disable DMA first. In fact, using DMA and normal transfer, I feel the effect is almost the same!

**Comment by sharandac** [comment]
Me to! I have change the line 104 from

`#if !defined(EXTERNAL_TFT_ESPI_LIBRARY) && !defined(LILYGO_BLOCK_ILI9488_MODULE)`

to

`#if !defined(EXTERNAL_TFT_ESPI_LIBRARY) && !defined(LILYGO_BLOCK_ILI9488_MODULE) && !defined(TWATCH_USE_PSRAM_ALLOC_LVGL)`

now it works fine for me.

**Comment by datacute** [comment]
Does a 32kHz clock signal work for low power BLE too?
https://github.com/espressif/esp-idf/issues/947#issuecomment-511264081
 The RTC can supply that can't it? The relevant ESP32 pin is used for something else though currently.

**Comment by sharandac** [comment]
I'm not sure. this was just an idea to increase the runtime with ble, currently about 10-12 hours. but the arduino environment does not support this at the moment. dynamic frequency scaling (DFS) is not enabled. I guess we will have to live with that.

**Comment by lewisxhe** [comment]
@robouden Then you also tell me your email, we will give you a free test, hope you can help us develop the firmware

**Comment by lewisxhe** [comment]
@sharandac Twatch lib has been updated, I will update the lvgl dedicated display function later

**Comment by robouden** [comment]
Lewisx He

My email address is rob@yr-design.biz.

regards,
Rob Oudendijk

**Comment by sharandac** [comment]
@lewisxhe Thanks a lot!

**Comment by apo76** [comment]
@lewisxhe : If you need one more beta tester, I'm in! ;o)
titanium2k4@hotmail.com .
Regards,
Attilio.

**Comment by lewisxhe** [comment]
We will send to you after the test, and email to contact you before sending @robouden  @sharandac 


@apo76  Sorry, there are no more free places! Sorry

**Comment by apo76** [comment]
@sharandac : I installed Gadgetbridge app after reading one of your post, but if I want notifications of missed phone call or messages on my watch, I need to set the BLE always on and I have a maximum autonomy of half a day, which is clearly not usable....is it the same on your side?
Best Regards,
Attilio.

**Comment by sharandac** [comment]
Yes, this is a problem with ESP32 and BLE. Unfortunately this cannot be changed :(

**Comment by cranphin** [comment]
> 
> 
> Yes, this is a problem with ESP32 and BLE. Unfortunately this cannot be changed :(

It would probably require the hardware update (32khz crystal), and using the esp32-idf, which means letting go of arduino environment.. :)
See: https://github.com/espressif/esp-idf/issues/947, not sure if the software side of that ever got implemented correctly either.

I tried the same thing with Gadgetbridge, and it does eat up the battery. It would be better if gadgetbridge would send any missed notification when the watch (re)connects on bluetooth, you wouldn't have live notifications, but at least you could check by waking the watch.
Setting autoreconnect in gadgetbridge works for me (the connecting part), but no missed notifications :)

**Comment by cranphin** [comment]
> Okay, I have given feedback!

@lewisxhe About the cracking shell, I see a very slight crack only on the outside, in the same place as the picture, without the shell having been under much pressure. I wonder if it's thick enough, but: A. there was a problem with the plastic molding, causing stress, or B. with the design it's just a tiny bit too tight in the case, so there's always a bit too much pressure on that side.

**Comment by NorthernDIY** [comment]
@lewisxhe If you are still able to take suggestions for v2, a light sensor and a status led might be pretty useful additions.

If your board layout guy is feeling generous, even just breaking out a few of the unused IO pins on the ESP32 would be super helpful for any mods we might want to install.

I've actually dug into the hardware and added my own mods on GPIO2 (LED) and GPI34 (Light sensor).  There is enough space to mount them along side the IR transmitter.  I haven't developed any code to support it just yet aside from basic testing to make sure they work.
