### ISSUE TITLE
The bin file cannot work on my device.

### ISSUE THREAD

**Issue by THSLP13** [sharandac/My-TTGO-Watch#79]
I've cloned a file from your repository called 'ttgo-t-watch2020_v1.ino.bin'.
I use ESP32 DOWNLOAD TOOL to download,but when it finished,the serial port notice me as following lines.
--------------------------------------------------------
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
--------------------------------------------------------
=
These is my upload configuration.
--------------------------------------------------------
SPI Speed:80MHz
SPI Mode:QIO
Flash Size:128Mbit
Upload Speed:921600
Offset:0
--------------------------------------------------------
I'm sure the file I cloned has no problem,but only this file cannot work on my device.
Here's the CRC32 with no file name verify:65DD1483
Here are pictures(I use Operating System in Chinese).
Upload Tool.
![image](https://user-images.githubusercontent.com/62548119/91651062-53dc8900-eaba-11ea-8ee2-d82d1c957a52.png)
Serial Debug tool
![image](https://user-images.githubusercontent.com/62548119/91651086-9bfbab80-eaba-11ea-8ec0-998128b55f07.png)
---------------------------------------------------------
If there is something I haven't noticed,please comment,thX.
---------------------------------------------------------
From THSLP32.

**Comment by wlcims** [comment]
The offset must be set to 0x1000, you can use the following command line to try flash the watch(use esptool.py ):

```sh
esptool.py --chip esp32 --port COM4 erase_flash
esptool.py --chip esp32 --port COM4 --baud 460800 write_flash -z 0x1000 ttgo-t-watch2020_v1.ino.bin
```
