### ISSUE TITLE
SPIFFS does not remount after format when rebooting with recently blanked flash.

### ISSUE THREAD

**Issue by NorthernDIY** [sharandac/My-TTGO-Watch#87]
If you erase the flash, it will format it as you'd expect on boot up, but it does not remount it afterwards.  Attempts to write settings later while running will fail.  It will work normally on the next reboot as you'd expect.

Here is what I did to fix it, probably not the most elegant solution.

`
splash_screen_stage_update( "init spiff", 20 );
    if ( !SPIFFS.begin() ) {        
        splash_screen_stage_update( "format spiff", 30 );
        SPIFFS.format();
        splash_screen_stage_update( "format spiff done", 40 );
        delay(500);
        bool remount_attempt = SPIFFS.begin();
        if (!remount_attempt){
            splash_screen_stage_update( "Err: SPIFF Failed", 0 );
            delay(3000);
            ESP.restart();
        }
    }
`

**Comment by sharandac** [comment]
Fixed in Version 2020090401. Thanks a lot!
