### ISSUE TITLE
convert this pio project to arduino IDE project ?

### ISSUE THREAD

**Issue by picpic020960** [sharandac/My-TTGO-Watch#95]
Bonjour ,
could someone do that?
thanks in advance
Regards

**Comment by ua6ahp** [comment]
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library - it is a "Arduino-ready" library. Read how to configure Arduino IDE on the above page.
SimpeWatch can be loaded from examples - TTGO TWatch Library -> LVGL -> SimpleWatch. 

Before uploading, you may need to uncomment the line

**//#define LILYGO_WATCH_2020_V1 // To use T-Watch2020 , please uncomment this line**

in config.h file.

But there will be no additional applications in the firmware. But the interface is more convenient there.

**Comment by jakub-vesely** [comment]
Hi, 
My I ask you what is the motivation for this request? I am just curious about that because I can't to see any advantage .
Thank you, Jakub

**Comment by ua6ahp** [comment]
Not everyone is ready to get started with platformio. Therefore, they ask ...
But this project is a little tricky for arduino ide ...
